### ISSUE TITLE
Error when kick ?

### ISSUE THREAD

**Issue by Heroiik62** [Fireflies/MaintenanceMode#3] opened 2015-03-28 18:53 UTC
[19:42:58] [Craft Scheduler Thread - 8/WARN]: Exception in thread "Craft Scheduler Thread - 8" 
[19:42:58] [Craft Scheduler Thread - 8/WARN]: org.apache.commons.lang.UnhandledException: Plugin MaintenanceMode v1.0.3b generated an exception while executing task 63
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Asynchronous player kick!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
	at org.bukkit.craftbukkit.v1_8_R2.entity.CraftPlayer.kickPlayer(CraftPlayer.java:218)
	at de.albionco.maintenance.bukkit.BukkitPlugin.kick(BukkitPlugin.java:126)
	at de.albionco.maintenance.bukkit.EnableRunnable.run(EnableRunnable.java:67)
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by Albioncode** [comment] 2015-03-30 12:22
Thanks for the report, will fix this today!

**Comment by JohOply** [comment] 2015-04-21 17:20
Hi

I have the same error. I use the lastest version of Spigot (1.8.3-b419)

[19:15:55 WARN]: org.apache.commons.lang.UnhandledException: Plugin MaintenanceMode v1.0.3b generated an exception while executing task 170
at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.IllegalStateException: Asynchronous player kick!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
at org.bukkit.craftbukkit.v1_8_R2.entity.CraftPlayer.kickPlayer(CraftPlayer.java:218)
at de.albionco.maintenance.bukkit.BukkitPlugin.kick(BukkitPlugin.java:126)
at de.albionco.maintenance.bukkit.EnableRunnable.run(EnableRunnable.java:67)
at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more

**Comment by cosha** [comment] 2015-04-21 21:36
snap, completely forgot to do this.

**Comment by cosha** [comment] 2015-04-21 21:48
@Heroiik62 @JohOply please could you try [this](https://drone.io/github.com/cosha/MaintenanceMode/files/target/Maintenance.jar) JAR and let me know if it fixes the bug? I won't be able to test it for a few days due to limited hardware at my disposal (attempted to edit and compile via my iPhone, not pretty lol)

**Comment by JohOply** [comment] 2015-04-24 13:09
Thanks to be quick

I'd test it 5 times, it seems work without bug !

Another request : could you add all messages in config.yml ? There are some messages that we can't modify currently :)

**Comment by JohOply** [comment] 2015-04-29 17:38
I have found another bug : during the countdown, nobody can speak into the chat, like it is disable, but all messages are display at the end of the countdown

**Comment by Albioncode** [comment] 2015-04-29 17:41
Ah, that's what I was afraid would happen which is why I wrote it the way I did.
Will have to see how I can work around that

**Comment by Fireflies** [comment] 2015-08-11 13:33
The project maintainer (@ElieTGM) has not replied since issue creation, closing the issue and marking as unresolved. Please report the incident in the discussion section [here][spigot-thread].

[spigot-thread]: https://www.spigotmc.org/resources/maintenancemode.2548/

**Closed** 2015-08-11 13:34 UTC
Labels: bug, redirected, unresolved
